name: Python Package using Conda

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64 
      - run: python graphviz
      - run: python xlsxwriter
      - run: python pathlib
      - run: python webbrowser
      - run: python pandas
      - run: python pdfkit
      - run: python word2number
      - run: python nltk
      - run: python main.py
