name: Python Package using Conda

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64 
      - run: pip install graphviz
      - run: pip install xlsxwriter
      - run: pip install pandas
      - run: pip install pdfkit
      - run: pip install word2number
      - run: pip install nltk
      - run: .\cmd.sh
